### ISSUE TITLE
pretty print to text file?

### ISSUE THREAD

**Issue by joreg** [aaronpowell/dotnet-delice#13]
helo aaron,

thanks for this great project!

i see how i can get the json to a file but is there also a way to get the pretty print into a file?

**Comment by aaronpowell** [comment]
The pretty print is intended to be human readable, not machine readable, hence why it's for display not saving.

Easiest solution is to redirect the output:

```sh
$> dotnet delice >> output.txt
```

**Comment by joreg** [comment]
great, thanks, didn't know about the >>
