### ISSUE TITLE
.NET 5.0 compatible version

### ISSUE THREAD

**Issue by McTristan** [aaronpowell/dotnet-delice#27]
Hello,

is it possible to tick the ".NET 5.0" checkbox (and maybe the dotnetcore3.**1** checkbox as well) and publish a new version? 
The current version is limited to .NET Core 3.0 - which works with the .NET Core 3.1 installed but not with .NET 5.0 - I would need to have an older runtime version installed as well when using the the dotnet-delice tool.

**Comment by aaronpowell** [comment]
Sure, I should bump the version to the latest runtime. Will add it to my todo list

**Comment by aaronpowell** [comment]
Released 1.6.0 today which bumps to `net5.0` as the TFM.
