### ISSUE TITLE
.NET SDK (5.0.400), Failed to generate the dependency graph

### ISSUE THREAD

**Issue by oscarwest** [aaronpowell/dotnet-delice#29]
Hello,
Thank you for maintaining this great project. 

Unfortunately we've run into some problems, it seems like in 1.6.0 of the tool, relative multi-level ProjectReference paths don't work with .NET SDK 5.0.400.
These paths work with 1.6.0 and .NET SDK 3.1.407.
One-level paths `..\something.csproj` seem to work.

Only tested on OSX with csproj `<TargetFramework>netcoreapp3.1</TargetFramework>`

Example:

1.6.0 + 3.1.407, works fine
```XML
<ItemGroup>
  <ProjectReference Include="..\..\src\Example.Application\Example.Application.csproj" />
</ItemGroup>
```

1.6.0 + 5.0.400, doesn't work, gives error after some time
```XML
<ItemGroup>
  <ProjectReference Include="..\..\src\Example.Application\Example.Application.csproj" />
</ItemGroup>
```
Error:
```
⇒  dotnet delice --json
Failed to generate the dependency graph for '/Users/oscarwest/projects/exampleProject/test/Example.Tests'.
Ensure that the project has been restored and compiled before running delice.
delice only supports SDK project files (.NET Core, NETStandard, etc.), not legacy MSBuild ones (common for .NET Framework).
```

1.6.0 + 5.0.400, works fine, note the prefix \ path which **essentially ignores the reference**.
```XML
<ItemGroup>
  <ProjectReference Include="\..\..\src\Example.Application\Example.Application.csproj" />
</ItemGroup>
```

OS Info
```shell
⇒  sw_vers
ProductName:	macOS
ProductVersion:	11.2.3
BuildVersion:	20D91
```

I noticed some changes to path stuff here: https://github.com/aaronpowell/dotnet-delice/commit/96fb0eb86d6a4a00ca172061cdeda4583cf71b49#diff-357e52cc01d8127f42410c332d0964638746c570620d19c39d715ff5b79db069R8
Maybe this mucked something?

Thank you again.

**Comment by aaronpowell** [comment]
Just to confirm - if your csproj is using a TFM of `netcoreapp3.1` it works, but if you change it to `net5.0` it'll fail?

Any chance you've got a sample repo I can look at?

**Comment by oscarwest** [comment]
The TFM is always netcoreapp3.1, it just fails when using the NET 5.0 SDK.

**Comment by joreg** [comment]
Same here. First many thanks for creating delice!

We've got a solution (~50 projects) that used to go through delice fine until changing everything to .NET6 (was .NET4.72 before). i can tell that even delice 1.5.2 was working well previously. but now with .NET6 even a change to latest delice 1.8.0 causes exactly the above mentioned error.

unfortunately the project is private. is there any chance we could get more verbose output for the error? or any way we could help debug the issue?

**Comment by joreg** [comment]
@aaronpowell when it throws the above error. would it be possible to write out the name of the project that caused the issue? i'd hope this would allow us to narrow down the issue.
