### ISSUE TITLE
Misspelled word in console output

### ISSUE THREAD

**Issue by KeitoDev** [aaronpowell/dotnet-delice#32]
In ConsoleOutput.fs there is a reference to "occurances" which should be "occurrences" instead. This typo is sent to output, as opposed to being internal to the codebase.

Link: https://github.com/aaronpowell/dotnet-delice/blob/4f68247b7646abd479926265854ca9c5a57656f1/src/DotNetDelice/ConsoleOutput.fs#L10

**Comment by aaronpowell** [comment]
Fixed and pushed out https://github.com/aaronpowell/dotnet-delice/releases/tag/v1.7.1 with it
