### ISSUE TITLE
seperate property for url in json output

### ISSUE THREAD

**Issue by yassinjabri** [aaronpowell/dotnet-delice#9]
url sould be a seperate property and value in json output

**Comment by aaronpowell** [comment]
In an ideal world there would be no URL ever output, that's just a hangover from packages that haven't been migrated across (and can't be determined by looking at the license itself).

Is there a specific scenario that you're wanting to use this for?

**Comment by yassinjabri** [comment]
Yes it is. I neet to create a list of all used packages with package name, version, license url and license type. This list i have to generate from time to time for deocumentation requirementts. A separate url property ist helpfull to generate an html page for example.

**Comment by aaronpowell** [comment]
Given that only a subset of the packages will have URL's, will that not be a problem for you? Or are you only concerned about linking to non-OSI licenses, and OSI licenses like MIT or Apache 2.0 are fine to inline the SPDX?

**Comment by yassinjabri** [comment]
In my opinion it is better to seperate package name and url. The result would be a clean package name and url to the license file. If there is a need to combine them, you always have the option to generate an individual output from the json output. I think its more flexible.

**Comment by aaronpowell** [comment]
Part of the 1.3.0 release.
